### ISSUE TITLE
Integration with vue-formio

### ISSUE THREAD

**Issue by arrancardnell** [formio/bootstrap3#8]
I'm currently trying to integrate vue-formio into an existing project which is already using Bootstrap 3. 

I've tried several methods to override the form styling with this package but haven't been very successful, could you please provide some advice (or possible documentation) on how this can be integrated with the vue-formio package?

**Comment by arrancardnell** [comment]
Okay, I found a solution for anyone who hits a similar issue.

```import { Formio } from "vue-formio/node_modules/formiojs";
import bootstrap3 from "@formio/bootstrap3";

Formio.use(bootstrap3);
```

Not sure if this is the ideal method, and perhaps someone can confirm/deny whether this is best way of doing it, but it works!

**Comment by travist** [comment]
That is the way to do it. Thanks @arrancardnell
